BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[UsersP1] (
    [id] INT NOT NULL IDENTITY(1,1),
    [login] NVARCHAR(50) NOT NULL,
    [password] NVARCHAR(150) NOT NULL,
    [salt] NVARCHAR(150) NOT NULL,
    [acces] BIT NOT NULL,
    [refrechtoken] NVARCHAR(max),
    CONSTRAINT [UsersP1_id_key] UNIQUE NONCLUSTERED ([id]),
    CONSTRAINT [UsersP1_login_key] UNIQUE NONCLUSTERED ([login])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
